/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creencias;

import javax.swing.JOptionPane;

/**
 *
 * @author antonio
 */
public class grafica extends javax.swing.JFrame {

    /**
     * Creates new form grafica
     */
    public grafica() {
        initComponents();
        setTitle("Creencias de los Adventista del 7mo día");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Broadway", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton1.setText("La palabra de Dios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(32, 19, 289, 23);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton2.setText("La Deidad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(32, 48, 289, 23);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton3.setText("Dios el Padre");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(32, 77, 289, 23);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton4.setText("Dios el Hijo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(32, 106, 289, 23);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton5.setText("Dios el Espíritu Santo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(32, 135, 289, 23);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton6.setText("La creación");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(32, 164, 289, 23);

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton7.setText("La naturaleza humana");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(32, 193, 289, 23);

        jButton8.setBackground(new java.awt.Color(204, 255, 204));
        jButton8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton8.setText("El gran conflicto");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(32, 222, 289, 23);

        jButton9.setBackground(new java.awt.Color(204, 255, 204));
        jButton9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton9.setText("La vida, muerte y resusrreción de Cristo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(32, 251, 289, 23);

        jButton10.setBackground(new java.awt.Color(204, 255, 204));
        jButton10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton10.setText("La experiencia de la Salvación");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(32, 280, 289, 23);

        jButton11.setBackground(new java.awt.Color(204, 255, 204));
        jButton11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton11.setText("Crecer en Cristo");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(32, 309, 289, 23);

        jButton12.setBackground(new java.awt.Color(204, 255, 204));
        jButton12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton12.setText("La iglesia");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(32, 338, 289, 23);

        jButton13.setBackground(new java.awt.Color(204, 255, 204));
        jButton13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton13.setText("El remanente y su misión");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(32, 367, 289, 23);

        jButton14.setBackground(new java.awt.Color(204, 255, 204));
        jButton14.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton14.setText("La unidad en el cuerpo de Cristo");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(32, 396, 289, 23);

        jButton15.setBackground(new java.awt.Color(204, 255, 204));
        jButton15.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton15.setText("El bautismo");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(379, 19, 249, 23);

        jButton16.setBackground(new java.awt.Color(204, 255, 204));
        jButton16.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton16.setText("La Cena del Señor");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(379, 48, 249, 23);

        jButton17.setBackground(new java.awt.Color(204, 255, 204));
        jButton17.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton17.setText("Los dones y ministerios espirituales");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(379, 77, 249, 23);

        jButton18.setBackground(new java.awt.Color(204, 255, 204));
        jButton18.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton18.setText("El don de profecía");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18);
        jButton18.setBounds(379, 106, 249, 23);

        jButton19.setBackground(new java.awt.Color(204, 255, 204));
        jButton19.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton19.setText("La ley de Dios");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19);
        jButton19.setBounds(379, 135, 249, 23);

        jButton20.setBackground(new java.awt.Color(204, 255, 204));
        jButton20.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton20.setText("El sábado");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20);
        jButton20.setBounds(379, 164, 249, 23);

        jButton21.setBackground(new java.awt.Color(204, 255, 204));
        jButton21.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton21.setText("La mayordomía");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21);
        jButton21.setBounds(379, 193, 249, 23);

        jButton22.setBackground(new java.awt.Color(204, 255, 204));
        jButton22.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton22.setText("La conducta cristiana");
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton22);
        jButton22.setBounds(379, 222, 249, 23);

        jButton23.setBackground(new java.awt.Color(204, 255, 204));
        jButton23.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton23.setText("El martimonio y la familia");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton23);
        jButton23.setBounds(379, 251, 249, 23);

        jButton24.setBackground(new java.awt.Color(204, 255, 204));
        jButton24.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton24.setText("El ministerio de Cristo en el Santuario Celestial");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(379, 280, 249, 23);

        jButton25.setBackground(new java.awt.Color(204, 255, 204));
        jButton25.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton25.setText("La segunda venida de Cristo");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton25);
        jButton25.setBounds(379, 309, 249, 23);

        jButton26.setBackground(new java.awt.Color(204, 255, 204));
        jButton26.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton26.setText("La muerte y la resurrección (Humanidad)");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton26);
        jButton26.setBounds(379, 338, 249, 23);

        jButton27.setBackground(new java.awt.Color(204, 255, 204));
        jButton27.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton27.setText("El milenio y el fin del pecado");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton27);
        jButton27.setBounds(379, 367, 249, 23);

        jButton28.setBackground(new java.awt.Color(204, 255, 204));
        jButton28.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton28.setText("La Tierra Nueva");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28);
        jButton28.setBounds(379, 396, 249, 23);

        jButton29.setBackground(new java.awt.Color(204, 255, 204));
        jButton29.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton29.setText("Cerrar");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton29);
        jButton29.setBounds(310, 490, 75, 23);

        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/12167657_897724210265278_561651816_n.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 680, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        JOptionPane.showMessageDialog(null, "El salario del pecado es la muerte. Pero Dios, el único que es imortal, concederá vida\n eterna a Sus redimidos. Hasta aquel día, la muerte es un estado inconsciente para\n todas las personas. (I Tim. 6:15 y 16; Rom. 6:23; I Cor. 15:51-54; Ecles. 9:5 y 6; Sal.\n 146:4; I Tes. 4:13-17; Rom. 8:35-39; Juan 5:28 y 29; Apoc. 20:1-10; Juan 5:24).");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "Las Sagradas Escrituras, el Antiguo y el Nuevo Testamento, son la Palabra de Dios escrita,\n dada por inspiración divina por intermedio de profetas de Dios que hablaron\n y escribieron al ser movidos por el Espíritu Santo. \n(II Pedro 1:20 y 21; II Tim. 3:16 y 17; Sal. 119:105; Prov. 30:5 y 6; Isa. 8:20; Juan 10:35; 17:17; I Tes. 2:13; Heb. 4:12.", "Creencias de los Adventistas de 7mo día)", 1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        dispose();

    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Hay un sólo Dios: Padre, Hijo y Espíritu Santo, una unidad de tres Personas coeternas.\n Dios es inmortal, omnipotente, omnisciente, encima de todo, y siempre presente.\n (Deut. 6:4; 29:29; Mat. 28:19; II Cor. 13:13; Efes. 4:4-6; I Pedro 1:2; I Tim. 1:17; Apoc. 14:6 y 7)", "Creencias de los Adventistas de 7mo día", 1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "Dios, el Eterno Padre, es el Creador, el Originador, el Mantenedor y el Soberano de toda la creación.\n Él es justo y santo, compasivo y clemente, tardo en airarse, y grande en constante amor y fidelidad.\n (Gén. 1:1; Apoc. 4:11; I Cor. 15:28; Juan 3:16; I Juan 4:8; I Tim. 1:17: Éxo. 34:6 y 7; Juan 14:9)", "Creencias de los Adventistas de 7mo día", 1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(null, "Dios, el Hijo Eterno, se encarnó en Jesucristo. Por medio de Él se crearon todas las\n cosas, se reveló el carácter de Dios, se efectuó la salvación de la humanidad y se juzga el mundo.\n Jesús sufrió y murió en la cruz por nuestros pecados y en nuestro lugar, fue resucitado\n entre los muertos y ascendió para administrar en el santuario celestial a nuestro favor.\n Vendrá otra vez para la liberación final de Su pueblo y la restauración de todas las cosas.\n (Juan 1:1-3 y14; 5:22; Col. 1:15-19; Juan 10:30; 14:9; Rom. 5:18; 6:23; II Cor. 5:17-21;\n Lucas 1:35; Filip. 2:5-11; I Cor. 15:3 y 4; Heb. 2:9-18; 4:15; 7:25; 8:1 y 2; 9:28; Juan 14:1-3; I Ped. 2:21; Apoc. 22:20).", "Creencias de los Adventistas de 7mo día", 1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(this, "Dios, el Espíritu Santo, desempeñó una parte activa con el Padre y el Hijo en la\n Creación, Encarnación y Redención. Inspiró a los escritores de las Escrituras. Llenó\n de poder la vida de Cristo. Atrae y convence a los seres humanos; y los que se\n muestran sensibles, son renovados y transformados por Él, a imagen de Dios. \nConcede dones espirituales a la Iglesia. (Gén. 1:1 y 2; Lucas 1:35; II Pedro 1:21; \nLucas 4:18; Hechos 10:38; II Cor. 3:18; Efes. 4:11 y 12; Atos 1:8; Juan 14:16-18 y 26; \n15:26 y 27; 16:7-13; Rom. 1:1-4)");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JOptionPane.showMessageDialog(this, "Dios es el Creador de todas las cosas y reveló en las Escrituras el relato auténtico de\nSu actividad creadora. En seis días hizo el Señor los Cielos y la Tierra y todo lo que \ntiene vida sobre la Tierra, y descansó el séptimo día de esa primera semana. (Gén. \n 1;2; Éxo. 20:8-11; Sal. 19:1-6; 33:6 y 9; 104; Heb. 11:3; Juan 1:1-3; Col. 1:16 y 17).");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JOptionPane.showMessageDialog(this, "El hombre y la mujer fueron formados a imagen de Dios con individualidad y con el \npoder y la libertad de pensar y actuar. Como han sido creados como seres libres, \ncada uno es una unidad indivisible de cuerpo, mente y alma, y dependiente de Dios \nen cuanto a la vida, respiración y todo lo demás. Cuando nuestros primeros padres \ndesobedecieron a Dios, negaron su dependencia de Él y cayeron de sua elevada \nposición abajo de Dios. La imagen de Dios en ellos, fue desfigurada, se volvieron \nmortales. Sus descendientes comparten esa naturaleza caída y de sus \nconsecuencias. (Gén. 1:26-28; 2:7; Sal. 8:4-8; Hechos 17:24-28; Gén. 3; Sal. 51:5; \n Rom. 5:12-17; II Cor. 5:19 y 20).");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(this, "Toda la humanidad está involucrada en un gran conflicto entre Cristo y Satanás, en \ncuanto al carácter de Dios, Su Ley y Su soberanía sobre el Universo. Ese conflicto se \noriginó en el Cielo, cuando un ser creado, dotado de libertad de elección, por \nexaltación propia, se convirtió en Satanás, el adversario de Dios, y condujo la \nrebelión de una parte de los ángeles. Él introdujo el espíritu de rebelión en este \nmundo. Observado por toda la Creación, este mundo se convirtió en el palco del \nconflicto universal, dentro del cual será finalmente reivindicado el Dios de amor. \n(Apoc. 12:4-9; Isa. 14:12-14; Ezeq. 28:12-18; Gén. 3; Gén. 6-8; II Pedro 3:6; Rom. 1:19-\n32; 5:19-21; 8:19-22; Heb. 1:4-14; I Cor. 4:9).");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JOptionPane.showMessageDialog(this, "En la vida de Cristo, de perfecta obediencia a la voluntad de Dios, y en Su sufrimiento, \nmuerte y resurrección, Dios proveyó el único medio de expiación del pecado humano, \nde modo que los que aceptan esa expiación por fe, puedan tener vida eterna, y toda \nla Creación comprenda mejor el infinito y santo amor del Creador. (Juan 3:16; Isa. 53; \nII Cor. 5:14, 15 y 19-21; Rom. 1:4; 3:25; 4:25; 8:3 y 4; Filip. 2:6-11; I Juan 2:2; 4:10; Col. 2:15).");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        JOptionPane.showMessageDialog(this, "En infinito amor y misericordia, Dios permitió que Cristo se convirtiese en pecado por \nnosotros, para que en Él fuésemos hechos justicia de Dios. Guiados por el Espíritu \nSanto reconocemos nuestra pecaminosidad, nos arrepentimos de nuestras \ntransgresiones y tenemos fe en Jesús como Señor y Cristo, como Sustituto y Ejemplo. \nEsta fe que acepta la salvación, viene del poder de la Palabra y es el don de la gracia \nde Dios. Por medio de Cristo somos justificados y libertados del dominio del pecado.\nPor medio del Espíritu, nacemos de nuevo y somos justificados. Permaneciendo en \nÉl, participamos de la naturaleza divina y tenemos la seguridad de la salvación, ahora \ny en el Juizo. (Sal. 27:1; Isa. 12:2; Jonas 2:9; Juan 3:16; II Cor. 5:17-21; Gál. 1:4; 2:19 y\n20; 3:13; 4:4-7; Rom. 3:24-26; 4:25; 5:6-10; 8:1-4, 14, 15, 26 y 27; 10:7; I Cor. 2:5; 15:3 \n y 4; I Juan 1:9; 2:1 y 2; Efes. 2:5-10; 3:16-19; Gál. 3:26; Juan 3:3-8; Mat. 18:3; I Pedro 1:23; 2:21; Heb. 8:7-12).");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        JOptionPane.showMessageDialog(this, "Por su muerte en la cruz, Jesús triunfó sobre las fuerzas del mal. Él, que durante su \nministerio terrenal subyugó los espíritus demoníacos, ha quebrantado su poder y \nasegurado su condenación final. La victoria de Jesús nos da la victoria sobre las \nfuerzas del mal que aún tratan de dominarnos, mientras caminamos con él en paz, \ngozo y en la seguridad de su amor. Ahora, el Espíritu Santo mora en nosotros y nos \ncapacita con poder. Entregados continuamente a Jesús como nuestro Salvador y \nSeñor, somos libres de la carga de nuestras acciones pasadas. Ya no vivimos en las \ntinieblas, ni en el temor de los poderes malignos, ni en la ignorancia y falta de sentido \nde nuestro antiguo estilo de vida. En esta nueva libertad en Jesús, somos llamados a \ncrecer a la semejanza de su carácter, manteniendo diariamente comunión con él en \noración, alimentándonos de su Palabra, meditando en ella y en su providencia, \ncantando sus alabanzas, reuniéndonos juntos para adorar, y participando en la \nmisión de la iglesia. Al darnos en amoroso servicio a aquellos que nos rodean y al dar \ntestimonio de su salvación, Cristo, en virtud de su presencia constante con nosotros \npor medio del Espíritu, transforma cada uno de nuestros momentos y cada una de \nnuestras tareas en una experiencia espiritual (Sal. 1:1, 2; 23:4; 77:11, 12; Col. 1:13, \n14: 2:6, 14, 15; Luc. 10:17-20; Efe. 5:19, 20; 6:12-18; 1 Tes. 5:23; 2 Ped. 2:9; 3:18; 2 \nCor. 3:17, 18; Fil. 3:7-14; 1 Tes. 5:16-18; Mat. 20:25-28; Juan 20:21; Gál. 5:22-25; \nRom. 8:38, 39; 1 Juan 4:4; Heb. 10:25).\n");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        JOptionPane.showMessageDialog(this, "La Iglesia es la comunidad de creyentes que confiesan a Jesucristo como Señor y\n Salvador. Nos unimos para adorar, para comunión, para instrucción en la Palabra,\npara celebrar la Cena del Señor, para el servicio a toda la humanidad y para la\n proclamación mundial del Evangelio. La Iglesia es la Familia de Dios. La Iglesia es el \n cuerpo de Cristo. (Gén. 12:3; Hechos 7:38; Mat. 21:43; 16:13-20; Juan 20:21 y 22;\n Hechos 1:8; Rom. 8:15-17; I Cor. 12:13-27; Efes. 1:15 y 23; 2:12; 3:8-11 y 15; 4:11-15). ");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        JOptionPane.showMessageDialog(this, "La Iglesia universal se compone de todos los que verdaderamente creen en Cristo; \npero, en los últimos días, un remaneciente ha sido llamado, a fin de guardar los \nmandamientos de Dios y la fe de Jesús. Este remaneciente anuncia la llegada de la\nhora del Juicio, proclama la salvación por medio de Cristo y predice la aproximación\nde Su segundo advenimiento. (Mar. 16:15; Mat. 28:18-20; 24:14; II Cor. 5:10; Apoc. \n12:17; 14:6-12; 18:1-4; Efes. 5:22-27; Apoc. 21:1-14).");

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        JOptionPane.showMessageDialog(this, "La Iglesia es un cuerpo con muchos miembros, llamados de toda nación, tribu, lengua \ny pueblo. Todos somos iguales en Cristo. Mediante la revelación de Jesucristo en las \nEscrituras, compartimos la misma fe y esperanza y extendemos un solo testimonio \npara todos. Esta unidad encuentra su fuente en la unidad del Dios triuno, que nos\n adoptó como Sus hijos. (Sal. 133:1; I Cor. 12:12-14; Hechos 17:26 y 27; II Cor. 5:16 y\n17; Gál. 3:27-29; Col. 3:10-15; Efes. 4:1-6; Juan 17:20-23; Santiago 2:2-9; I Juan 5:1). ");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        JOptionPane.showMessageDialog(this, "Por el bautismo confesamos nuestra fe en la muerte y en la resurrección de Jesucristo\n y testimoniamos nuestra muerte al pecado y nuestro propósito de andar en novedad\nde vida, siendo aceptados como miembros por Su Iglesia. Y por inmersión en el agua\n se sigue la instrucción en las Escrituras Sagradas y la aceptación de sus enseñanzas.\n(Mat. 3:13-16; 28:19 y 20; Hechos 2:38; 16:30-33; 22:16; Rom. 6:1-6; Gál. 3:27; I Cor.\n 12:13; Col. 2:12 y 13; I Pedro 3:21).");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        JOptionPane.showMessageDialog(this, "La Cena del Señor es una participación en los emblemas del cuerpo y de la sangre\n de Jesús, como expresión de fe en Él, nuestro Señor y Salvador. La preparación\nincluye el examen de conciencia, el arrepentimiento y la confesión. El Maestro\n instituyó la Ceremonia del lavamiento de pies para representar renovada purificación,\npara expresar la disposición de servir uno al otro en humildad semejante a la de\n Cristo, y para unir nuestros corazones en amor. (Mat. 26:17-30; I Cor. 11:23-30; 10:16\ny 17; Juan 6:48-63; Apoc. 3:20; Juan 13:1-17). ");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        JOptionPane.showMessageDialog(this, "Dios concede a todos los miembros de Su Iglesia, en todas las épocas, dones\n espirituales. Siendo otorgados por la actuación del Espíritu Santo, el cual distribuye a\ncada miembro como le place, los dones proveen todas las aptitudes y ministerios que\n la Iglesia necesita para cumplir sus funciones divinamente ordenadas. Algunos \nmiembros son llamados por Dios y dotados por el Espíritu para funciones reconocidas\n por la Iglesia en ministerios pastorales, evangélicos, apostólicos y de enseñanza.\n(Rom. 12:4-8; I Cor. 12:9-11, 27 y 28; Efes. 4:8 y 11-16; II Cor. 5:14-21; Hechos 6:1-7;\n I Tim. 2:1-3; I Pedro 4:10 y 11; Col. 2:19; Mat. 25:31-36). ");
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        JOptionPane.showMessageDialog(this, "Uno de los dones del Espíritu Santo es la profecía. Este don es una característica de\n la Iglesia remaneciente y fue manifestado en el ministerio de Ellen G. White. Como la\n mensajera del Señor, sus escritos son una continua y autorizada fuente de verdad y \nproporcionan consuelo, orientación, instrucción y corrección a la Iglesia. (Joel 2:28 y \n29; Hechos 2:14-21; Heb. 1:1-3; Apoc. 12-17; 19:10).");
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        JOptionPane.showMessageDialog(this, "Los grandes principios de la Ley de Dios son incorporados en los Diez Mandamientos\n y ejemplificados en la vida de Cristo. Expresan el amor, la voluntad y los propósitos\n de Dios acerca de la conducta y de las relaciones humanas, y son obligatorios a \ntodas las personas, en todas las épocas. Esos preceptos constituyen la base del\n concierto de Dios con Su pueblo y la norma del juicio de Dios. (Éxo. 20:1-17; Mat.\n 5:17; Deut. 28:1-14; Sal. 19:7-13; Juan 14:15; Rom. 8:1-4; I Juan 5:3; Mat. 22:36-40;\n Efes. 2:8).");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        JOptionPane.showMessageDialog(this, "El bondadoso Creador, después de los seis dias de la Creación, descansó el séptimo\n día e instituyó el Sábado para todas las personas, como recordativo de la Creación. El\n cuarto mandamiento de la inmutable Ley de Dios requiere la observancia de este\n sábado del séptimo día como día de descanso, adoración y ministerio, en armonía\n con la enseñanza y práctica de Jesús, el Señor del Sábado. (Gén. 2:1-3; Éxo. 20:8-11;\n 31:12-17; Lucas 4:16; Heb. 4:1-11; Deut. 5:12-15; Isa. 56:5 y 6; 58:13 y 14; Lev. 23:32;\n Mar. 2:27 y 28).");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        JOptionPane.showMessageDialog(this, "Somos mayordomos de Dios, responsables por el uso apropiado del tiempo y de las\n oportunidades, capacidades y posesiones, y de las bendiciones de la Tierra y sus\n recursos que Él colocó bajo nuestro cuidado. Reconocemos el derecho de propiedad\n de parte de Dios, por medio del fiel servicio a Él y a nuestros semejantes, y\n devolviendo los diezmos y dando ofrendas para la proclamación de Su Evangelio y\n para la manutención y el crecimiento de Su iglesia. (Gén. 1:26-28; 2:15; Hageo 1:3-\n11; Mal. 3:8-12; Mat. 23:23; I Cor. 9:9-14).");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        JOptionPane.showMessageDialog(this, "Somos llamados para ser un pueblo piadoso, que piensa, siente y actúa de acuerdo\n con los principios del Cielo. Para que el Espíritu recree en nosotros el carácter de\n nuestro Señor, solo nos involucramos con aquellas cosas que producirán en nuestra\n vida, pureza, salud y alegría semejantes a las de Cristo. (I Juan 2:6; Efes. 5:1-13;\n Rom. 12:1 y 2; I Cor. 6:19 y 20; 10:31; I Tim. 2:9 y 10; Lev. 11:1-47; II Cor. 7:1; I Pedro\n 3:1-4; II Cor. 10:5; Filip. 4:8).");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        JOptionPane.showMessageDialog(this, "El casamiento fue divinamente establecido en el Edén y confirmado por Jesús como\n unión vitalicia entre un hombre y una mujer, en amoroso compañerismo. Para el\n cristiano, el compromiso matrimonial es con Dios, y con el cónyuge, y solamente debe\n ser asumido entre parejas que comparten la misma fe. Referente al divorcio, Jesús\n enseñó que la persona que se divorcia del cónyuge, a no ser por causa de\n fornicación, y se casa con otro, comete adulterio. Dios bendice a la familia y quiere\n que sus miembros se ayuden uno al otro a alcanzar completa madurez. Los padres\n deben educar sus hijos a amar al Señor y a obedecerle. (Gén. 2:18-25; Deut. 6:5-9;\n Juan 2:1-11; Efes. 5:21-33; Mat. 5:31 y 32; 19:3-9; Prov. 22:6; Efes. 6:1-4; Mal. 4:5 y 6;\n Mar. 10:11 y 12; Lucas 16:18; I Cor. 7:10 y 11).");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        JOptionPane.showMessageDialog(this, "Hay un santuario en el Cielo. En él, Cristo intercede en nuestro favor, haciendo\n accesibles a los creyentes los beneficios de Su sacrifício expiatorio ofrecido una vez\n por todas, en la cruz. Él es nuestro gran Sumo Sacerdote y comenzó Su ministerio\n intercesor en ocasión de Su ascensión. En 1844, a final del período profético de los\n 2.300 días, inició la segunda y última etapa de Su ministerio expiatorio. El jucio\n investigador revela a los seres celestiales quien entre los muertos será digno de\n formar parte en la primera resurrección. También se hace manifesto quien, entre los\n vivos, está preparado para la traslación a Su reino eterno. La terminación del\n ministerio de Cristo señalará el fin del tiempo de gracia para los seres humanos,\n antes del Segundo advenimiento. (Heb. 1:3; 8:1-5; 9:11-28; Dan. 7:9-27; 8:13 y 14;\n 9:24-27; Núm. 14:34; Ezeq. 4:6; Mal. 3:1; Lev. 16; Apoc. 14:12; 20:12; 22:12).");

    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        JOptionPane.showMessageDialog(this, "La segunda venida de Cristo es la bendita esperanza de la Iglesia. La venida del\n Salvador será literal, personal, visible y universal. (Tito 2:13; Juan 14:1-3; Hechos 1:9-\n11; I Tes. 4:16 y 17; I Cor. 15:51-54; II Tes. 2:8; Mat. 24; Mar. 13; Lucas 21; II Tim. 3:1-5;\n Joel 3:9-16; Heb. 9:28).");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        JOptionPane.showMessageDialog(this, "El milenio es el reinado de mil años de Cristo con Sus santos, en el Cielo, entre la\n primera y la segunda resurrección. Durante este tiempo serán juzgados los impíos\n muertos. Al fin de ese período, Cristo con Sus Santos y la Ciudad Santa descenderán\n del Cielo a la Tierra. Los impíos muertos serán entonces resucitados y, con Satanás y\n sus ángeles, cercarán la ciudad; pero el fuego de Dios los consumirá y purificará la\n Tierra. El Universo quedará eternamente libre del pecado y de los pecadores. (Apoc.\n 20; Zac. 14:1-4; Mal. 4:1; Jer. 4:23-26; I Cor. 6; II Pedro 2:4; Ezeq. 28:18; II Tes. 1:7-9;\n Apoc. 19:17, 18 y 21).");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        JOptionPane.showMessageDialog(this, "En la Nueva Tierra, en que habita la justicia, Dios proveerá un hogar eterno para los\n remidos y un ambiente perfecto para vida, amor, alegría y aprendizaje eternos, en Su\n presencia. (II Pedro 3:13; Gén. 17:1-8; Isa. 35; 65:17-25; Mat. 5:5; Apoc. 21:1-7; 22:1-5;\n 11:15).");
    }//GEN-LAST:event_jButton28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
